distSeq <- seq(0, 1, by = .05)
partA <- list()
partA$prior <- function(x) dgamma(x, shape = .25, rate = .5)
partA$posterior <- function(x) dgamma(x, shape = 20.25, rate = 102.5)
partB <- list()
partB$prior <- function(x) dgamma(x, shape = .25, rate = .025)
partB$posterior <- function(x) dgamma(x, shape = 20.25, rate = 102.025)
png('../Desktop/Projects/Stat135/Chapter8/output/Problem62Plot_a.png', type = 'cairo')
plot(distSeq, partA$prior(distSeq), type = 'l', ylim = c(0, 10))
lines(distSeq, partA$posterior(distSeq), type = 'l', lty = 2)
dev.off()
png('../Desktop/Projects/Stat135/Chapter8/output/Problem62Plot_b.png', type = 'cairo')
plot(distSeq, partB$prior(distSeq), type = 'l', ylim = c(0, 10))
lines(distSeq, partB$posterior(distSeq), type = 'l', lty = 2)
dev.off()
